gha: update go versions to 1.19, 1.20, 1.21
Note that go1.13 has reached EOL a long time ago; removing that version,
as packages are no longer compatible with it:

    go get github.com/philhofer/fwd
    # golang.org/x/tools/internal/gocommand
    Error: ../../../go/src/golang.org/x/tools/internal/gocommand/invoke.go:399:62: undefined: os.ErrProcessDone
    Error: Process completed with exit code 2.

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>